FROM node:24-bookworm-slim AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build
FROM nginx:1.29-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
