FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn==23.0.0
COPY app.py .
EXPOSE 8080
CMD ["gunicorn","app:app","--bind","0.0.0.0:8080"]
